---
# tasks file for anansi

- name: Setting ssh port
  lineinfile: dest=/etc/ssh/sshd_config regexp='^Port 22' line='Port {{ssh_port}}'
  notify: restart sshd

- name: Adding repository
  apt_repository: repo='ppa:ubuntu-lxc/daily' state=present

- name: Install software
  apt: name={{ item }} state=present
  with_items:
    - aufs-tools
    - git
    - build-essential
#    - mercuria
    - libpcap-dev
    - linux-image-3.19.0-22-generic
    - linux-image-extra-3.19.0-22-generic
    - lxc
    - lxc-dev
 #   - criu
    - protobuf-c-compiler
    - tmux
    - tor

- name: Install iptables rules
  copy: src=iptables.rules dest=/etc/iptables.rules
  notify: restart iptables

- name: Create LXC template container
  command: lxc-create -t download -n {{ anansi_lxc_template_name }} -- --dist {{ anansi_lxc_template_os }} --release {{ anansi_lxc_template_os_release }} --arch {{ anansi_lxc_template_arch }} creates=/var/lib/lxc/{{ anansi_lxc_template_name }}/

- name: Install resolv.conf for lxc template
  copy: src=resolv.conf dest=/var/lib/lxc/{{ anansi_lxc_template_name }}/rootfs/etc/resolv.conf

- name: Configure lxc template
  template: src=lxc_config.yml dest=/var/lib/lxc/{{ anansi_lxc_template_name }}/config

- name: Fetch random hostnames for hostname generation
  command: curl https://gist.githubusercontent.com/nl5887/41ec1a4aa38bd6715f69/raw/servernames -v -o /tmp/hostnames

- name: Get hostname
  command: shuf -n 1 /tmp/hostnames
  register: random_hostname

- name: Set hostname for lxc template
  command: echo {{ random_hostname.stdout }} > /var/lib/lxc/{{ anansi_lxc_template_name }}/rootfs/etc/hostname creates=/var/lib/lxc/{{ anansi_lxc_template_name }}/rootfs/etc/hostname

- name: Updating lxc template
  command: chroot /var/lib/lxc/troje_base/rootfs apt-get update -y

- name: Upgrading lxc template
  command: chroot /var/lib/lxc/troje_base/rootfs apt-get upgrade -y

- name: Installing necessary packages in the lxc template
  command: chroot /var/lib/lxc/troje_base/rootfs apt-get install -y openssh-server curl wget apache2

- name: Setting up SSH in the lxc template
  lineinfile: dest=/etc/ssh/sshd_config regexp='^PermitRootLogin' line='PermitRootLogin yes'

- name: Setting up root user in lxc template
  lineinfile: dest=/var/lib/lxc/troje_base/rootfs/etc/shadow regexp='^root:' line='root:$6$nBzvBNnm$aq34X2l8i10sGr/VpN/orJ5zRkC96y.juReKpcFi5Do/GWinDEjjU4fB2o5Y6eTJLU25pNKZ.H2BnfhoaD/dg0:16765:0:99999:7:::'

- name: Setting up ubuntu user in lxc template
  lineinfile: dest=/var/lib/lxc/troje_base/rootfs/etc/shadow regexp='^ubuntu:' line='ubuntu:$6$KfLbOPJd$3yyJ9f59CKdLcXxkHiXqqFwhvQmqeeeEyYKB2hlXOyGBBgcHXZmASopHf8tF6Pje0bLwhSnHSuMNngFaMwuF9/:16765:0:99999:7:::'


- name: Install limits.conf
  copy: src=limits.conf dest=/etc/security/limits.conf

- name: Create honeytrap directory
  command: mkdir /opt/honeytrap/ creates=/opt/honeytrap/

- name: Create honeytrap perm directory
  command: mkdir /opt/honeytrap/perm/ creates=/opt/honeytrap/perm/

- name: Create honeytrap logs directory
  command: mkdir /opt/honeytrap/logs/ creates=/opt/honeytrap/logs/

- name: Create honeytrap profiles directory
  command: mkdir /opt/honeytrap/profiles/ creates=/opt/honeytrap/profiles/

- name: Create honeytrap scripts directory
  command: mkdir /opt/honeytrap/scripts/ creates=/opt/honeytrap/scripts/

- name: Create honeytrap certs directory
  command: mkdir /opt/honeytrap/certs/ creates=/opt/honeytrap/certs/

- name: Generate certificate
  command: openssl req -x509 -new -newkey rsa:{{anansi_certificate_key_size}} -days {{anansi_certificate_days}} -nodes -keyout /opt/honeytrap/certs/cert.key -out /opt/honeytrap/certs/cert.crt -subj {{anansi_certificate_subject}} creates=/opt/honeytrap/certs/cert.crt

- name: Generate SSH keys
  command: ssh-keygen -h -N "" -f /opt/honeytrap/perm/perms creates=/opt/honeytrap/perm/perms

- name: Copy rc.local
  copy: src=rc.local dest=/etc/rc.local mode=0655



